"""rename NEGOTIATING to TALKING, add APPROVAL_PENDING

Revision ID: 086ea9c3161e
Revises: 69d0c9e9c334
Create Date: 2026-05-15 16:15:57.555517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086ea9c3161e'
down_revision: Union[str, None] = '69d0c9e9c334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Migrate existing data before altering column constraints
    op.execute("UPDATE streamers SET status = 'TALKING' WHERE status = 'NEGOTIATING'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('streamers', 'status',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('NEW', 'REQUEST_SENT', 'REPLIED', 'TALKING', 'APPROVAL_PENDING', 'APPROVED', 'ACTIVE', 'REJECTED', 'DEAD', name='funnelstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("UPDATE streamers SET status = 'TALKING' WHERE status = 'APPROVAL_PENDING'")
    op.execute("UPDATE streamers SET status = 'NEGOTIATING' WHERE status = 'TALKING'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('streamers', 'status',
               existing_type=sa.Enum('NEW', 'REQUEST_SENT', 'REPLIED', 'TALKING', 'APPROVAL_PENDING', 'APPROVED', 'ACTIVE', 'REJECTED', 'DEAD', name='funnelstatus', native_enum=False),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
