"""extend streamers with funnel statuses

Revision ID: 69d0c9e9c334
Revises: 7d7863f344f7
Create Date: 2026-05-08 14:46:15.465983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69d0c9e9c334'
down_revision: Union[str, None] = '7d7863f344f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streamers', sa.Column('profile_url', sa.String(length=500), nullable=True))
    op.add_column('streamers', sa.Column('followers', sa.BigInteger(), nullable=True))
    op.add_column('streamers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('streamers', sa.Column('last_status_change_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('streamers', 'platform',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('TIKTOK', 'INSTAGRAM', 'YOUTUBE', 'TELEGRAM', name='platform', native_enum=False),
               existing_nullable=True)
    op.alter_column('streamers', 'geo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('LATAM', 'BRASIL', 'ARGENTINA', 'COLOMBIA', 'MEXICO', 'PERU', 'CHILE', 'ECUADOR', 'BOLIVIA', 'PANAMA', 'VENEZUELA', 'ESPANA', 'USA', 'OTHER', name='geo', native_enum=False),
               existing_nullable=True)
    # Migrate existing status values to new funnel enum before altering column type
    op.execute("UPDATE streamers SET status = 'NEW' WHERE status IN ('active', 'inactive', 'paused')")
    op.execute("UPDATE streamers SET status = 'NEW' WHERE status IS NULL")
    op.alter_column('streamers', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'paused', name='streamerstatus'),
               type_=sa.Enum('NEW', 'REQUEST_SENT', 'REPLIED', 'NEGOTIATING', 'APPROVED', 'ACTIVE', 'REJECTED', 'DEAD', name='funnelstatus', native_enum=False),
               existing_nullable=False)
    op.create_unique_constraint('uq_streamers_profile_url', 'streamers', ['profile_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # Partial rollback: drop added columns and revert platform/geo to plain VARCHAR.
    # status is NOT reverted to native PG ENUM (streamerstatus) — that type may
    # no longer exist in the DB after upgrade; leaving status as VARCHAR is safe.
    op.drop_constraint('uq_streamers_profile_url', 'streamers', type_='unique')
    op.drop_column('streamers', 'last_status_change_at')
    op.drop_column('streamers', 'updated_at')
    op.drop_column('streamers', 'followers')
    op.drop_column('streamers', 'profile_url')
    op.alter_column('streamers', 'platform',
               existing_type=sa.Enum('TIKTOK', 'INSTAGRAM', 'YOUTUBE', 'TELEGRAM', name='platform', native_enum=False),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('streamers', 'geo',
               existing_type=sa.Enum('LATAM', 'BRASIL', 'ARGENTINA', 'COLOMBIA', 'MEXICO', 'PERU', 'CHILE', 'ECUADOR', 'BOLIVIA', 'PANAMA', 'VENEZUELA', 'ESPANA', 'USA', 'OTHER', name='geo', native_enum=False),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
