"""init

Revision ID: 7d7863f344f7
Revises: 
Create Date: 2026-04-27 13:09:46.238260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7863f344f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'project_manager', 'lead_manager', 'analyst', 'manager', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('geo', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('new', 'contacted', 'in_process', 'approved', 'rejected', name='leadstatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streamers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('geo', sa.String(length=100), nullable=True),
    sa.Column('tiktok_link', sa.String(length=500), nullable=True),
    sa.Column('tg_link', sa.String(length=500), nullable=True),
    sa.Column('tg_channel', sa.String(length=255), nullable=True),
    sa.Column('bot_link', sa.String(length=500), nullable=True),
    sa.Column('stockity_login', sa.String(length=255), nullable=True),
    sa.Column('stockity_password', sa.String(length=255), nullable=True),
    sa.Column('price_per_stream', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('wallet_address', sa.String(length=500), nullable=True),
    sa.Column('wallet_type', sa.Enum('usdt_trc20', 'usdt_erc20', 'btc', 'other', name='wallettype'), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'paused', name='streamerstatus'), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('streamer_id', sa.BigInteger(), nullable=False),
    sa.Column('days_of_week', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('stream_time', sa.String(length=10), nullable=True),
    sa.Column('tiktok_link', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['streamer_id'], ['streamers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streams',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('streamer_id', sa.BigInteger(), nullable=False),
    sa.Column('stream_link', sa.String(length=500), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('views_youtube', sa.Integer(), nullable=True),
    sa.Column('views_tiktok', sa.Integer(), nullable=True),
    sa.Column('users_bot', sa.Integer(), nullable=True),
    sa.Column('users_channel', sa.Integer(), nullable=True),
    sa.Column('registrations', sa.Integer(), nullable=True),
    sa.Column('deposits', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'cancelled', name='paymentstatus'), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['streamer_id'], ['streamers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streams')
    op.drop_table('schedule')
    op.drop_table('streamers')
    op.drop_table('leads')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
